In [1]:
# import Package
import pandas as pd
import numpy as np


In [2]:
pd.__version__

'2.2.2'

In [3]:
number_series = pd.Series([1, 2, 3, 4, 5])
print(number_series)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [4]:
number_series= pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'],name='Number')
print(number_series)

a    1
b    2
c    3
d    4
e    5
Name: Number, dtype: int64


In [5]:
print(number_series[0])
print(number_series['a'])



1
1


<ipython-input-5-9d94995d9a79>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(number_series[0])


In [6]:
some_2D_array = np.random.randint(4,7,(7, 5))
print(some_2D_array)


[[6 4 5 5 6]
 [5 5 4 4 4]
 [6 5 6 5 6]
 [5 6 4 5 6]
 [5 4 6 5 6]
 [6 4 6 4 4]
 [6 4 6 5 6]]


In [7]:
first_dataframe = pd.DataFrame(some_2D_array, columns=['Akshay', 'Devashish', 'Divy', 'Monika','aradhya'])
print(first_dataframe)

   Akshay  Devashish  Divy  Monika  aradhya
0       6          4     5       5        6
1       5          5     4       4        4
2       6          5     6       5        6
3       5          6     4       5        6
4       5          4     6       5        6
5       6          4     6       4        4
6       6          4     6       5        6
